package com.pocketchat.models.enums.websocket;

public enum WebSocketEvent {
    JOINED_CONVERSATION_GROUP,
    LEFT_CONVERSATION_GROUP,
    UPLOADED_GROUP_PHOTO,
    CHANGED_GROUP_PHOTO,
    DELETED_GROUP_PHOTO,
    CHANGED_GROUP_DESCRIPTION,
    PROMOTE_GROUP_ADMIN,
    DEMOTE_GROUP_ADMIN,
    ADD_GROUP_MEMBER,
    REMOVE_GROUP_MEMBER,
    CHANGED_PHONE_NUMBER,
    EXISTING_CONTACT_JOINED
}
