package com.pocketchat.models.enums.websocket;

public enum WebSocketEvent {
    ADDED_TO_THE_CONVERSATION_GROUP,
    LEAVED_CONVERSATION_GROUP,
    UPLOADED_GROUP_PHOTO,
    CHANGED_GROUP_PHOTO,
    DELETED_GROUP_PHOTO,
    CHANGED_GROUP_DESCRIPTION,
    PROMOTE_GROUP_ADMIN,
    DEMOTE_GROUP_ADMIN,
    ADD_GROUP_MEMBER,
    REMOVE_GROUP_MEMBER,
    CHANGED_PHONE_NUMBER,
    EXISITNG_CONTACT_JOINED
}
