language: java

before_script:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

jobs:
  include:

  - stage: ☕ jdk.java.net - OpenJDK - GPL
    env: JDK=14
    script: source install-jdk.sh -F 14

after_script:
  - echo JAVA_HOME = ${JAVA_HOME}
  - echo PATH = ${PATH}
  - ls ${JAVA_HOME}
  - java -version
