language: java
install: true
dist: bionic

jdk:
  - oraclejdk14
  - openjdk14


script:
  - ./gradlew clean check
  - ./gradlew build
  - docker build -t tkhenghong/pocketchat .
  - sudo docker push tkhenghong/pocketchat:latest
