language: java

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

install:
  - source install-jdk.sh -F 14
  - export PATH=$JAVA_HOME/bin:$PATH
  - java -version
  - javac -version
