# Using Docker Compose as part of the Proof Concept to make sure everything is ready for deployment in 1
# single command.

# General problems:
# Binding port is already allocated:
# https://stackoverflow.com/questions/56285989/docker-compose-bind-failed-port-is-already-allocated

# Connect to MongoDB Docker from Spring Boot Docker:
# https://stackoverflow.com/questions/59330607/connect-to-docker-compose-mongodb-via-spring-boot-application

# MongoDB related guides & problems:

# How To Deploy And Manage MongoDB With Docker:
# https://phoenixnap.com/kb/docker-mongodb

# Spring Boot Docker:
# https://spring.io/guides/topicals/spring-boot-docker/

# Spring Boot + Mongodb + Docker Compose:
# https://nirajsonawane.github.io/2019/12/16/Spring-Boot-Mongodb-Docker-Compose/

# How to run Spring Boot and MongoDB in Docker using Docker Compose:
# https://dev-pages.info/how-to-run-spring-boot-and-mongodb-in-docker-using-docker-compose/

# https://stackoverflow.com/questions/47901561/how-to-run-mongodb-and-mongo-express-with-docker-compose
# https://kb.sloppy.io/en/articles/1313693-setting-up-mongodb-and-mongo-express-on-sloppy-io

# No more smallfiles option in latest mongo container.
# https://github.com/jsbroks/coco-annotator/issues/244

# Mount MongoDB data Volume:
# https://stackoverflow.com/questions/35400740/how-to-set-docker-mongo-data-volume

# RabbitMQ related issues:

# https://zgadzaj.com/development/docker/docker-compose/containers/rabbitmq
# https://github.com/laradock/laradock/issues/2048

# Interesting articles related to Docker:

# Dockerize your Java Application:
# https://runnable.com/docker/java/dockerize-your-java-application

# NOTE: You must go through:
# https://hub.docker.com/r/bitnami/kafka/
# to install new certificates for the server for secure Kafka authentication (SASL).

version: "3"

networks:
  app-tier:
    driver: bridge

services:
  pocketChat:
    image: tkhenghong/pocketchat:latest
    restart: always
    networks:
      - app-tier
    ports:
      - 8888:8888
    # - 27017:27017
    # - 5672:5672
    # - 15672:15672
    depends_on:
      - mongo
      # - mongo-express
      - rabbitmq
      - zookeeper
    links:
      - mongo
      - rabbitmq
  mongo:
    image: mongo
    container_name: mongodb
    hostname: mongo
    ports:
      - 27017:27017
    restart: always
    # command: --smallfiles
    volumes:
      # - ./data/db:/data/db
      - /tmp/pocketChatMongoData:/data/db
#    environment:
      # MONGODB_URI: mongodb://mongodb
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app-tier
  mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
#      environment:
#        ME_CONFIG_MONGODB_SERVER: mongo
#        ME_CONFIG_MONGODB_PORT: 27017
#        ME_CONFIG_MONGODB_AUTH_DATABASE: admin
#        ME_CONFIG_MONGODB_AUTH_USERNAME: root
#        ME_CONFIG_MONGODB_AUTH_PASSWORD: password
      depends_on:
        - mongo
      links:
        - mongo
      networks:
        - app-tier
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
#      - ${DATA_PATH_HOST}/rabbitmq/etc/:/etc/rabbitmq/
#      - ${DATA_PATH_HOST}/rabbitmq/data/:/var/lib/rabbitmq/
#      - ${DATA_PATH_HOST}/rabbitmq/logs/:/var/log/rabbitmq/
     - /tmp/rabbitmq/etc/:/etc/rabbitmq/
     - /tmp/rabbitmq/data/:/var/lib/rabbitmq/
     - /tmp/rabbitmq/logs/:/var/log/rabbitmq/
#    environment:
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
#    environment:
#      - ZOO_ENABLE_AUTH=yes
#      - ZOO_SERVER_USERS=kafka
#      - ZOO_SERVER_PASSWORDS=kafka_password
#      - ALLOW_ANONYMOUS_LOGIN=no
    volumes:
    - /tmp/zookeeper/data:/bitnami/zookeeper
    networks:
      - app-tier
  kafka:
    image: 'bitnami/kafka:latest'
    hostname: tkhenghong.com
    ports:
      - '9092'
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_CFG_LISTENERS=SASL_SSL://:9092
#      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://:9092
#      - KAFKA_ZOOKEEPER_USER=kafka
#      - KAFKA_ZOOKEEPER_PASSWORD=kafka_password
#      - KAFKA_CLIENT_USER=user
#      - KAFKA_CLIENT_PASSWORD=password
#      - KAFKA_CERTIFICATE_PASSWORD=certificatePassword123
    volumes:
      - /tmp/kafka/data:/bitnami/kafka
      - './kafka.keystore.jks:/opt/bitnami/kafka/conf/certs/kafka.keystore.jks:ro'
      - './kafka.truststore.jks:/opt/bitnami/kafka/conf/certs/kafka.truststore.jks:ro'
    links:
      - zookeeper
    depends_on:
      - zookeeper
    networks:
      - app-tier

# For Zookeeper and Kafka in Docker, we are using bitnami/zookeeper and bitnami/kafka, both have 50M downloads
