# https://stackoverflow.com/questions/59330607/connect-to-docker-compose-mongodb-via-spring-boot-application
version: "3"

networks:
  app-tier:
    driver: bridge

services:
  java:
    build:
      context: ./
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
  pocketChat:
    image: tkhenghong/pocketchat:latest
    restart: always
    networks:
      - app-tier
    depends_on:
      - mongo
      - mongo-express
      - rabbitmq
      - zookeeper
  mongo:
    image: mongo
    container_name: mongodb
    hostname: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
#      - ./data/db:/data/db
      - /Users/tkhenghong/data/pocketChatMongoData:/Users/tkhenghong/data/pocketChatMongoData
    environment:
#      MONGODB_URI: mongodb://mongodb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app-tier
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
# https://zgadzaj.com/development/docker/docker-compose/containers/rabbitmq
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
    - 5672:5672
    - 15672:15672
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - 2181:2181
    networks:
      - app-tier
  kafka:
      image: 'bitnami/kafka:latest'
      ports:
      - 9092:9092
      environment:
        KAFKA_ADVERTISED_HOST_NAME: 192.168.0.195
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_PORT: 9092
        KAFKA_ADVERTISED_PORT: 9092
      depends_on:
        - zookeeper
      networks:
        - app-tier

# For Zookeeper and Kafka in Docker, we are using bitnami/zookeeper and bitnami/kafka, both have 50M downloads



